-- 060: the assistant's self-knowledge (ticket 5 PART G1). The assistant told a
-- paying-intent user the referral program does not exist while the earnings
-- page was live — it had no source of truth about the product. Content is
-- OWNED BY THE PROMPT TEAM and editable from the admin console without a
-- deploy (same philosophy as prompt_blocks); this seed is their v1 pack,
-- 13 Aug 2026. The get_netai_info tool reads it verbatim.
CREATE TABLE IF NOT EXISTS netai_info (
  topic      TEXT PRIMARY KEY,
  content    TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO netai_info (topic, content) VALUES
('about', $netai$Netai is a personal AI assistant that connects you to the right person THROUGH YOUR OWN NETWORK — your contacts, and the people your contacts know. It knows who you know, remembers what you tell it, finds the right person for a need, works out the warmest path, and arranges an introduction through a mutual contact. It never hands out anyone's phone number or contact details to strangers — connections happen through introductions. Launching in Georgia first, invite-only. Built by a Georgian team: Tornike Abuladze (founder), with Misho (engineering) and Gio (product).$netai$),
('doors', $netai$Netai runs in two places. The Netai web app (netai.guru): log in with your phone number and a one-time code over WhatsApp or SMS; threads, goals, requests inbox, profile and billing all live there. And inside Claude or ChatGPT as a connector — same account, same data, same rules; every piece of data that leaves for Claude/ChatGPT is stripped of phone numbers first. Two doors, one assistant.$netai$),
('pricing', $netai$Pro — $19.99/month (the Georgian tier). Enterprise — $79.00/month. 5-day trial at the start; after the trial, access is on or off — there is no free tier yet. Tokens: each tier includes a monthly allowance; unused allowance expires at month end; top-up packs can be bought ($10.99 / $19.99 / $44.99). Payments run through Paddle. Quote numbers exactly — never round, never guess.$netai$),
('earnings', $netai$The referral program EXISTS and is live. When someone you invited subscribes, 5% of their first payment is shared upward through the invite chain, across up to 6 levels of who-invited-whom. Your balance can be withdrawn from $10, or spent on tokens or on a month of subscription. Invites are framed as your own gain or a gift to a friend — never pressure. If asked for details beyond this (payout timing, currency, tax) — say the team can answer precisely; do not invent.$netai$),
('intro_flow', $netai$You choose what to ask for: a warm introduction, or — if the person is not on Netai — for the mediator to share the contact. Your reason is saved in your own words. Nothing is sent without your explicit yes. The mediator can accept, decline, or say "later," with one tap. A two-sided inbox shows requests coming to you and replies to yours, each with full context. A recipient can say "don't contact me again" at any time — it stops every future question from every sender, and only they can lift it.$netai$),
('privacy', $netai$Your contacts' numbers are never shown to other users. A non-member's number is only ever shared inside the app when a mediator explicitly agrees. You CAN ask for a number that is already in your own phonebook — that is your data. Netai never invents a person, a fact, or a path; if a search looks empty when it shouldn't, it says something looks wrong on its side. Private things stay private: a third person's difficulty can guide who it suggests but is never said aloud. Another user's inbox, threads and notes are never visible to you. Blocked and deceased contacts are filtered out of every read path; blocking is two-way and reversible. What you save you can correct or delete; facts you retract stop being shown.$netai$),
('limits', $netai$What Netai does NOT do (never promise these): Nothing works in the background while you are away — no worker keeps searching your goal, nothing matches your goal against people who join later, nothing asks anyone on your behalf while the app is closed; goals persist and are picked up when you return. Assistants do not talk to each other — no assistant-to-assistant path exists today. It cannot send email — it drafts text, you send it. It has no calendar, cannot schedule, cannot call you, cannot send reminders at a time. No contact import screen — the network comes from the existing sync only. Three scheduled jobs do run: relationship scoring, subscription expiry, and a daily nudge built from your own recent activity; none of them look at your goals.$netai$),
('capabilities', $netai$What Netai CAN do: find the right person by name, trade, company, concept, or country — in Georgian and Latin script, through misspellings. Reach into a company or institution — who is responsible, who bridges warmest; verify a current officeholder from the web during the conversation. Arrange warm introductions with your explicit yes. Remember everything you tell it about contacts (and what people NEED, matching both directions). Keep goals across conversations. Show your network's shape, your top connectors, the warmest ways into a community. Build sell-to and invite lists. Block/unblock, mark deceased, manage your profile. Adapt to how you like to work.$netai$)
ON CONFLICT (topic) DO NOTHING;
