-- WHEN DID THIS BROWSER LAST SAY „I AM STILL HERE" — row 101, the half that
-- was missing.
--
-- ════════ THE PROBLEM THIS SOLVES, STATED EXACTLY ════════
--
-- One notification goes to EVERY row in `push_subscriptions` for a person, so
-- a row left behind by a browser that no longer exists makes every
-- notification arrive twice. Two accounts carry such rows today: 160584 has
-- five endpoints, 501 has three.
--
-- The server cannot tell a dead row from a live one. Measured on 24 September
-- across fourteen days of `push_deliveries`: `failed = 0` on every endpoint on
-- every day, INCLUDING two that visibly stopped existing. Apple and Google
-- accept a push to a dead address and answer „delivered". A row only ever dies
-- on a 404 or a 410, and those two have never said either.
--
-- `previous_endpoint` (ef5f173) fixed the case where a browser changes its
-- endpoint while it is running: it names the row it replaces and the server
-- deletes exactly that one. IT CANNOT REACH ROWS WRITTEN BEFORE IT, because
-- the browser that wrote them may never come back — an old install, a deleted
-- home-screen app. Nobody will ever name those.
--
-- ════════ WHY A TIMESTAMP IS A FACT AND NOT A GUESS ════════
--
-- `savePushSubscription` already backfills `device_id` and `user_agent` on a
-- re-subscribe (COALESCE on conflict), so the server DOES hear from a browser
-- that is still in use. It simply never wrote down when. With this column it
-- does, and then the dangerous question becomes answerable WITHOUT guessing:
--
--     retire a row only when it has not been claimed for a long time
--     AND ANOTHER ROW FOR THE SAME PERSON HAS BEEN CLAIMED RECENTLY.
--
-- The second half is what makes it safe. It proves, for that person, that
-- claims are arriving at all — so „this one is silent" means the browser is
-- gone and not that the client never reports. Without it, a client that posts
-- only on a NEW subscription would make every row look dead and the rule would
-- delete somebody's only phone. The evidence has to come from the same person,
-- because that is the only place it cannot be wrong about.
--
-- Nothing here deletes anything. It records a date so that a later deletion can
-- be a fact with a reason, decided by a person, in the register (D44).
--
-- ════════ AND IT IS SELF-HEALING IF IT IS EVER WRONG ════════
--
-- Deleting a row that turns out to be live costs that device its notifications
-- until the person next opens the app — at which point it re-registers like
-- any new device. That is the bounded, recoverable direction, and it is worth
-- writing down before anybody presses anything.
ALTER TABLE push_subscriptions
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

-- Seeded from creation, not from NOW(): a row that has never been re-claimed
-- must not look as though it was claimed the minute this migration ran. That
-- would erase the very difference the column exists to record, on exactly the
-- four rows it was built for.
UPDATE push_subscriptions
   SET last_seen_at = created_at
 WHERE last_seen_at IS NULL;

-- ════════ ⚠️ 27 SEPTEMBER — THE SAFETY HALF HAS A HOLE, AND IT IS THE
--          DANGEROUS DIRECTION. READ THIS BEFORE ANY RETIREMENT RUNS. ════════
--
-- The rule above is:
--
--     retire a row only when it has not been claimed for a long time
--     AND ANOTHER ROW FOR THE SAME PERSON HAS BEEN CLAIMED RECENTLY.
--
-- The second half was written to prove „claims are arriving for this person,
-- so silence means the browser is gone". THE FRONTEND FOUND THAT THIS IS NOT
-- WHAT IT PROVES, and they found it in their own code rather than in mine.
--
-- Until 619c2ec (27 September) the client reported ONLY ON A FULL PAGE LOAD.
-- Not on SPA navigation, not periodically, not on return. And an INSTALLED APP
-- IS NOT LOADED — somebody leaves it open and comes back to it, which is
-- `visibilitychange`, not a load.
--
-- So a claim arriving for a person does NOT mean their client reports for
-- every surface they own. It means at least one of their surfaces does full
-- page loads. Take somebody with two: a browser tab that loads pages and
-- claims its row, and a home-screen app they live in and never reload.
--
--     the browser row      claimed recently      ✓ the rule's evidence
--     the installed row    silent for a month    ✓ the rule's target
--
-- Both halves are satisfied and THE ROW IT WOULD RETIRE IS THE PHONE THEY
-- ACTUALLY USE. The comparative test does not protect that case; it is what
-- selects it. „This endpoint has not asked for a month" could mean „this
-- person has not closed the app in a month", and the two are opposite facts
-- about whether the device matters to them.
--
-- ════════ WHAT THIS MEANS FOR THE DATE ════════
--
-- `last_seen_at` written BEFORE 27 September 19:13 UTC is not evidence of
-- absence. It is evidence about how somebody opens the app. The column did not
-- lie; it answered a question nobody had asked it.
--
-- The frontend now reports on RETURN as well as on load (five-minute floor),
-- so the timestamps become what this rule assumed they already were. But:
--
--   1. A session opened before their fix runs the OLD bundle until the person
--      reloads once. Those rows stay silent through no fault of the device.
--   2. The timestamps only start meaning „this device is gone" after a full
--      quiet window has passed WITH the new client in the field.
--
-- So the retirement planned for 8 October must not read anything recorded
-- before 27 September, and the quiet window has to be counted from the day the
-- new client actually reached people — not from the day this column shipped.
--
-- Nothing here deletes anything; it never did. The decision is a person's, in
-- the register (D44). This paragraph exists so that person is not deciding
-- from a number that means something other than it appears to.
